### ISSUE TITLE
JabFox button does not appear

### ISSUE THREAD

**Issue by gdanielea** [JabRef/JabFox#26]
Hi,

sorry if it is a stupid question, but after installing jabfox in firefox, nothing appears on the toolbar.

**Comment by tobiasdiez** [comment]
Is JabFox listed as an installed add-on (under Menu -> Add-ons)?
You can try to find the JabFox button under Menu -> Customize (at the bottom, left with a plus button as icon) -> search for JabRef icon.

Otherwise reinstalling the add-on might fix the problem.

**Comment by gdanielea** [comment]
Yes, it is installed and I have tried to look for the icon under Customize. I also tried to reinstall the addon, but to no avail.

**Comment by tobiasdiez** [comment]
You can try to restore the default toolbar under Menu -> Customize -> Restore defaults.
If this does not help, you might want to try out the solutions sketched here https://support.mozilla.org/en-US/questions/1087027. 
If all this does not help, then please copy the output from `about:support`

**Comment by tobiasdiez** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Comment by koppor** [comment]
![grabbed_20160707-143839](https://cloud.githubusercontent.com/assets/1366654/16653336/87cc5944-4450-11e6-8512-3833b7a40045.png)

**Comment by indradecastro** [comment]
just for the sake of confirmation,
I found the same issue (cant find JabFox button anywhere) under:
-Ubuntu 15.10
-Firefox 47.0
-Zotero add-on 4.0.29.10 installed
-(and JabRef 3.2, just in case it helps)

I installed the JabFox add-on twice with no button appearing.
thanks for good work :)
indra

**Comment by tobiasdiez** [comment]
@indradecastro The bug should be fixed in the most recent versions of JabFox. Do you still have no icon?

**Comment by indradecastro** [comment]
@tobiasdiez I've totally removed and reinstalled JabFox 1.1.0 today, but the result is identical, I can't find the button. Is the add on accesible another way (without button)?

**Comment by tobiasdiez** [comment]
I think I can reproduce the problem now. A fix will take some time since I'm currently on a conference/holidays. Sorry.

**Comment by indradecastro** [comment]
I can wait, that's OK.
I am eager to see how marvellously the add-on works.
cheers

**Comment by indradecastro** [comment]
any news?

**Comment by jrdunson** [comment]
I too, cannot see the icon!! It is still a bug
 - jrd

**Comment by vagnum08** [comment]
Hi, I had the same problem too. Though I managed to make the icon to appear. 

Strangely when you have the following option `Always use private browsing mode` enabled on Firefox the icon is missing, the moment you disable this option and do a restart on Firefox, the icon appears on the toolbar. 

Frankly, as soon as you re-enable the `Always use private browsing mode` option the icon goes missing again. 

This happens with wallabag v2 icon too.

**Comment by tobiasdiez** [comment]
@indradecastro @jrdunson which version of Firefox do you use? I noticed that Zotero has some problems in the recent Nightly versions (at least >= version 51). Do you have a Zotero icon but no JabFox icon?

@vagnum08 Thanks for the hint. I now enabled JabFox also in private windows (the new add-on version 1.1.1. should be available in a few days after it is reviewed by Mozilla).

**Comment by indradecastro** [comment]
I use Firefox 47.0, the last stable version offered for Ubuntu.
Indeed I have Zotero icon, and use it with no issue.
But no JabFox icon, which is still a mystery for me.

Thanks @tobiasdiez  for coming back to our problem.

**Comment by indradecastro** [comment]
As you might infer from my message on issue #28 the issue I was experiencing with the button is now solved. Unfortunately I am facing a new one now :'(
I will keep trying as this add-on is very promising.

**Comment by khalid-hussain** [comment]
I too have this problem.

Windows 10 64-bit
Firefox 54.0.1 (64-bit)

**Comment by wgeorg** [comment]
For me (Ubuntu 16.04, Firefox 54.0) JabFox didn't work with Zotero Connector. But using Zotero 4.0 Firefox Plugin as suggested in [#39](https://github.com/JabRef/JabFox/issues/39) solved the problem for me.

**Comment by khalid-hussain** [comment]
@wgeorg , Thanks for the tip. It works now.

**Comment by deisi** [comment]
It is either still not visible or I installed it wrongly. I don't see the icon as well.

Firefox:  56.0 (64-bit)
Jabref: 2.10
Ubuntu: 16.04

Zotero from: https://download.zotero.org/extension/zotero-4.0.29.21.xpi
but also tried the addon from the firefox addon store.
Is the Firefox Addon enogh? I find the Instructions quite unclear. I can easily install the Zotero Firefox addon, but installing Zotero itself is difficult under Ubuntu, since they only provide a precompiled binary, that you can run, but there is no installations script or anything.

**Comment by wgeorg** [comment]
@deisi 
as I described in my last post above the Zotero 4.0 Firefox plugin is the right one (https://download.zotero.org/extension/zotero-4.0.29.25.xpi). Disable in Firefox updating of this addon (about:addons -> click on "more" next to the zotero icon -> Set automatic updates to off) as well. Have you also set in the JabFox Addon settings the "Path to JabRef" ? If not check https://github.com/JabRef/JabFox#installation-and-configuration
I hope this is useful :-)

My config: Ubuntu 16.04, Firefox 56.0 (64-bit), JabRef 3.8.2

**Comment by deisi** [comment]
Okay, now I have it work together with JabRef 2.10, as it is the version shipped with Ubuntu by default. 

I also tried to use the current JabRef 4 version. After adjusting the path in the addon, it starts JabRef4, but nothing is added to the Database.

**Comment by jeslago** [comment]
For me the button suddenly disappeared yesterday.

Following @wgeorg remarks, I have managed to make the button appear. In my case, an automatic update of zotero had disabled it.

**Comment by deisi** [comment]
And I believe it will not be compatible with Firefox 57, because its a legacy Addon. (Good I made it work yesterday...)

**Comment by tobiasdiez** [comment]
With the rewrite of the add-on this issue should be fixed now. Note, however, that Linux and MacOS are not yet supported.

**Comment by lohae** [comment]
Hi,
I experience the same problem using Firefox 67//Win10/JabRef4.3.1.

There is just no button showing up. Any ideas?

**Comment by davidcbenson** [comment]
I have [opened a similar issue](https://github.com/JabRef/JabFox/issues/55), although perhaps not the same, and find there is a workaround. The problem is navigating away from the relevant window *and tab*. If I 1) reload the window, or 2) enter and leave reading mode, the button appears, in both cases staying on on the window and tab until fully loaded, the tab appears.

There may be two different bugs, but I'd try it. My version of the bug tends to appear when I open a window in the background.

**Comment by jamboo2017** [comment]
I have the same issue. JabFox button is never shown on my firefox. I have tried to reinstall the add-on several times.
Firefox v68.0.2 64-bit
The connection status shows "Communcation to JabRef successful!"
